---

- name: Provision an OS X system
  hosts: localhost
  become: no
  become_method: sudo
  vars_files:
    - env_vars/main.yml

  roles:
    - system
    - packages
    - applications
    - dotfiles
