---

- name: "Update Homebrew"
  homebrew:
    update_homebrew=yes
  become: false

- name: "Install some brews"
  homebrew:
    name={{ item.name|default(item) }} 
    state={{ item.state|default('present') }}
    install_options={{ item.install_options|default() }}
  with_items: "{{ homebrew_packages }}"

- name: "Install required node packages"
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items: "{{ npm_packages }}"

- name: "Install required python packages"
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ python_packages }}"

- name: "Install ruby"
  shell: "/usr/local/bin/ruby-install ruby"
