---
# vars file for applications

caskroom_dir: /usr/local/Caskroom

homebrew_cask_packages:
  - 1password
  - daisydisk
  - dash
  - docker
  - gimp
  - google-chrome
  - gpgtools
  - iterm2
  - keepingyouawake
  - little-snitch
  - micro-snitch
  - slack
  - spectacle
  - sublime-text
  - tunnelblick
  - vagrant
  - virtualbox
  - vlc
  - wireshark
