---

- include: disable-apple-callbacks.yml

- name: Download keyserver certs
  shell: 'curl -o /etc/sks-keyservers.netCA.pem https://sks-keyservers.net/sks-keyservers.netCA.pem'
  become: true

# Hides desktop items
- name: hide desktop items
  osx_defaults:
    domain: com.apple.Finder
    state: present
    key: CreateDesktop
    value: 0
    type: int

# Disable creation of .DS_Store files on network drives
- name: do not create .DS_Store on network shares
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    state: present
    value: "true"
    type: boolean

# Disable remote control infrared receiver. Requires re-login
- name: disable remote control infrared receiver
  osx_defaults:
    domain: /Library/Preferences/com.apple.driver.AppleIRController'
    state: present
    key: DeviceEnabled
    value: "false"
    type: boolean

# Modify 'natural' mouse scrolling (enable or disable). Requires re-login
- name: disable natural mouse scrolling
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    state: present
    value: "true"
    type: boolean

# This option is in System Preferences > Users & Groups > Guest User
- name: disable guest account
  osx_defaults:
    domain: /Library/Preferences/com.apple.loginwindow
    key: GuestEnabled
    state: present
    value: "false"
    type: boolean
  become: true

# This option is in System Preferences > Security & Privacy > General > Set Lock Message
- name: set a screen lock message
  osx_defaults:
    domain: /Library/Preferences/com.apple.loginwindow
    key: LoginwindowText
    state: present
    value: "If this computer is found contact {{ user_email }}"
    type: string
  become: true

# This option is in System Preferences > Security & Privacy > General > Require Password
- name: ask for password
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    state: present
    value: 1
    type: int

# This option is in System Preferences > Security & Privacy > General > Require Password
- name: ask for password immediately
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    state: present
    value: 0
    type: float

# Always show hidden files in Finder
- name: always show hidden files in finder
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    state: present
    value: "true"
    type: boolean
  become: true

# Disable Captive Portal assistant utility when connectivity can't be established on a new network
- name: disable Captive Portal assistant utility when connectivity can't be established on a new network
  osx_defaults:
    domain: com.apple.captive.control
    key: Active
    state: present
    value: "false"
    type: boolean
  become: true